baseURL = "https://shivjeet1.github.io/"
title = "Shivam Lavhale"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"

[params]
  enableThemeToggle = false
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/images/shivam1.jpg"
  customHeadHTML = """
    <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
    <link rel="stylesheet" href="/css/navbar.css">
    <link rel="stylesheet" href="/css/pureblack.css">
    <link rel="stylesheet" href="/css/math.css">
    <link rel="stylesheet" href="/css/skills.css">
  """

  description = "Still exploring, still learning, still building."
  author = 'Shivam Vishnu Lavhale'
  metaKeywords = ["blog", "shivjeet1", "hugo"]
  footer = "[shivjeet1](https://github.com/shivjeet1)"
  showBackToTopButton = true 

socialIcons = [ 
    #{name = "twitter", url = "https://x.com/shivjeet_1"},
    {name = "linkedin", url = "https://www.linkedin.com/in/shivam-lavhale"},
    {name = "github", url = "https://github.com/shivjeet1"},
    {name = "gmail", url = "mailto:shivamlavhalepatil@gmail.com"}
]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Skills"
    pre = "<span data-feather='layers'></span>"
    url = "/skills/"
    weight = 3

  [[menu.main]]
    name = "Blogs"
    pre = "<span data-feather='book-open'></span>"
    url = "/blogs/"
    weight = 4

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 5 

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false

[minify]
    minifyOutput = true


